### ISSUE TITLE
Enable Greenkeeper.io in all lander repos

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/formidable-landers#104]
https://greenkeeper.io/ will automatically submit pull requests when there are updates available for NPM dependencies. Provided we have CI set up with realistic tests, we should be able to tell whether it's a breaking change or not, and fix / merge accordingly.
- [x] spectacle-docs :star2: 
- [x] victory-docs :star2: 
- [x] radium-docs :star2:

**Comment by paulathevalley** [comment]
@bmathews Now that your sweet tests are set up :tada:, this would be a great next issue to tackle. The starred :star2: repos are the ones most likely to be updated frequently, so they would be good to do first.

**Comment by coopy** [comment]
I've split out the less important landers/repos in separate issues: 
- https://github.com/FormidableLabs/formidable-landers/issues/128
- https://github.com/FormidableLabs/formidable-landers/issues/129

The prerequisite to enabling Greenkeeper in a repo is that functional/acceptance tests are in place and being run as part of CI.

**Comment by paulathevalley** [comment]
Done!
