### ISSUE TITLE
Victory Docs Home Icon Issues

### ISSUE THREAD

**Issue by kylecesmat** [FormidableLabs/formidable-landers#116]
Two issues with the icons on the home page.

1. They are two different shades of charcoal, should probably be the same.
2. Misaligned on safari. Likely an issue with flexbox.

Chrome Icons:
![screen shot 2016-07-21 at 2 58 00 pm](https://cloud.githubusercontent.com/assets/1633837/17040259/9380fde0-4f53-11e6-9725-0b0f9f86bcdd.png)

Safari Icons:
![screen shot 2016-07-21 at 2 58 07 pm](https://cloud.githubusercontent.com/assets/1633837/17040273/9b6f3b48-4f53-11e6-87e1-b7fdd4799a3e.png)

**Comment by bmathews** [comment]
I think the color difference is from `:visited`!

**Comment by kylecesmat** [comment]
Ah! that'd make sense! Maybe then we change the visited style? The darker-contrast feels like a `:hover` state to me
