### ISSUE TITLE
Spectacle Editor Lander

### ISSUE THREAD

**Issue by rgerstenberger** [FormidableLabs/formidable-landers#125]
Only hard requirement is download links for .dmg and .exe install files.

Perhaps a title + short blurb + single screenshot followed by large download links.

**Comment by paulathevalley** [comment]
Question: Where are the download links? Where should the buttons point?

**Comment by paulathevalley** [comment]
I captured a .gif for drag & drop, and I will take a screenshot of a plot.ly chart that's integrated, but are there any other .gifs that are required for this page? 

![drag-drop](https://cloud.githubusercontent.com/assets/768965/17266685/1c22f34e-55b0-11e6-9848-45d94965640d.gif)

**Comment by rgerstenberger** [comment]
The downloadable files don't exist yet. They will eventually point to `.dmg` and `.exe` download files for installing Spectacle Editor.
