### ISSUE TITLE
Google Analytics is tracking the open-source routes incorrectly

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#138]
In Google Analytics, the routes are showing up _without_ the `/open-source/victory/` in front of them.

Actual: formidable.com/recipes
Expected: formidable.com/open-source/victory/recipes

![screen shot 2016-08-12 at 5 27 17 pm](https://cloud.githubusercontent.com/assets/768965/17640320/0d1db64c-60b2-11e6-96a0-490d5401eae2.png)

:sob:

**Comment by kylecesmat** [comment]
This might be caused by `react-ga` simply passing the `pathname` to google analytics? It looks like we could pass "document-path" as part of the `gaOptions` object https://github.com/react-ga/react-ga#example
