### ISSUE TITLE
Add Code of Conduct to all repos

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#143]

**Comment by rawrmonstar** [comment]
- [x] [**builder**](https://github.com/FormidableLabs/builder/pull/119)
- [ ] [**ecology**](https://github.com/FormidableLabs/ecology/pull/48) - need code reviews
- [x] [**radium**](https://github.com/FormidableLabs/radium/pull/821)
- [ ] **webpack-dashboard** - waiting on write access to repo
- [ ] **react-music** - waiting on write access to repo
