### ISSUE TITLE
Create a universal footer for all OSS Landers

### ISSUE THREAD

**Issue by eliseworthy** [FormidableLabs/formidable-landers#147]
- Footer should have space/Formidable branding
- Footer should have links to contact (hire us messaging) and careers
- Nav should look consistent across all OSS landers

**Comment by paulathevalley** [comment]
@eliseworthy Working on the footer now! The current footer always has the following:
> Made with love by 
> Formidable
> P.S. [We’re hiring](formidable.com/careers)

How should I include the contact (hire us messaging)?

**Comment by paulathevalley** [comment]
Current design:
<img width="829" alt="screen shot 2016-08-29 at 5 25 56 pm" src="https://cloud.githubusercontent.com/assets/768965/18071853/ad2f40e8-6e0d-11e6-979a-09de305ef974.png">

**Comment by paulathevalley** [comment]
Here's the light theme: 

<img width="1205" alt="screen shot 2016-08-29 at 5 32 04 pm" src="https://cloud.githubusercontent.com/assets/768965/18071946/8add48b8-6e0e-11e6-8e9b-c550feedc874.png">
