### ISSUE TITLE
Create subdomains for most important OSS projects

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/formidable-landers#16]
* [x] Forward projects.formidablelabs.com -> stack.formidable.com
* [ ] Forward projects.formidablelabs.com/x -> x.formidable.com
  * [x] http://victory.formidable.com 
  * [ ] http://radium.formidable.com
    * [ ] Add a CNAME file
    * [ ] Update DNS for radium.formidable.com to point to formidablelabs.github.io 
  * [x] http://builder.formidable.com
    * [x] Add a CNAME file
    * [x] Update DNS for builder.formidable.com to point to formidablelabs.github.io 
* [ ] Make sure that all github repos have links to x.formidable.com

**Comment by paulathevalley** [comment]
- [x] Forward projects.formidablelabs.com to http://stack.formidable.com/

**Comment by paulathevalley** [comment]
http://stack.formidable.com is up and live!

**Comment by paulathevalley** [comment]
No more subdomains! Moving to /open-source/*
