### ISSUE TITLE
Serve docs font-files from formidable.com

### ISSUE THREAD

**Issue by kylecesmat** [FormidableLabs/formidable-landers#162]
Right now, we're including a `fonts.css` in some of our projects, thus letting anyone copy our base-64'd font files :/

We should probably remove those and serve them from `formidable.com`? And maybe add some server-level logic to only allow serving the file to other `formidable.com` domains?

The two instances I know of:
https://github.com/FormidableLabs/formidable-playbook/blob/master/static/fonts.css
https://github.com/FormidableLabs/radium-docs/blob/master/static/fonts.css

**Comment by paulathevalley** [comment]
Currently, there is a `fonts.css` file being hosted on the WordPress side. Would it be worth pointing to that one? The alternative is hosting a file we control directly at `formidable.com/open-source/fonts.css`.

Agree that server-level logic to prevent the file being used elsewhere would be awesome!

**Comment by paulathevalley** [comment]
Asked Ui here: https://github.com/FormidableLabs/formidable.com/issues/265

**Comment by paulathevalley** [comment]
Fixed!
