### ISSUE TITLE
Add branding/style guide for Builder

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#41]
@ryan-roemer Do you have any preferences/ideas about how you want Builder to look? Modern? Whimsical? Austere? Cheeky? Warm? 

Are there existing competitors to Builder? Grunt? Gulp?

**Comment by ryan-roemer** [comment]
@paulathevalley -- No idea! There aren't really competitors -- grunt and gulp are "sort of" competitors (?)

Maybe modern / austere? When I think abstractly of builder it's like your command-in-chief, admiral, director or architect (writing blueprints) of how things will be for lots of constituents / people.

**Comment by paulathevalley** [comment]
Awesome! I can work with that.
