### ISSUE TITLE
Victory: Implement Radium SSR media queries

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/formidable-landers#47]
- Release new version of Radium (https://github.com/FormidableLabs/radium/pull/473 has the SSR fix)
- Implement necessary changes for radium lander

**Comment by paulathevalley** [comment]
> Before we can release a SSR MQ version of victory.formidable.com, we need to update all Victory components affected by the breaking Radium changes.: https://github.com/FormidableLabs/victory/issues/167

**Comment by coopy** [comment]
I'm going through component by component to test for breakages, but it's
looking like we don't need to make any changes outside of
`victory/docs/docs.jsx`.
tors 14 jan. 2016 kl. 17:44 skrev Paula Lavalle <notifications@github.com>:

**Comment by paulathevalley** [comment]
Done!
