### ISSUE TITLE
Deploy radium lander to `formidable.com/open-source/radium`

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/formidable-landers#50]
- Deploy radium lander to `radium.formidable.com` ("just like Victory")
- Forward `stack.formidablelabs.com/radium` to `radium.formidable.com`

**Comment by paulathevalley** [comment]
Update URL for SEO purposes!

**Comment by paulathevalley** [comment]
Task list for this PR:
- [ ] Create `radium-docs` repo 
- [ ] Import `radium-docs` into `formidable.com` 
- [ ] Deploy to http://formidable.com/open-source/radium 
- [ ] Update link in `radium` 
- [ ] Remove `/docs` in `radium`

**Comment by paulathevalley** [comment]
Closing in favor of https://github.com/FormidableLabs/radium-docs/issues/2
