### ISSUE TITLE
Move Flex and Flex-Item to this repo

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#55]
The same Flex components are being used in formidable.com and builder-docs repos, so move them here. 

TODO:
- [ ] Pass in custom media queries for the `small={} medium={} large={}` props on `Flex.Item`

[formidable.com/... flex.jsx](https://github.com/FormidableLabs/formidable.com/blob/master/client/components/flex.jsx)
[formidable.com/... flex-item.jsx]( https://github.com/FormidableLabs/formidable.com/blob/master/client/components/flex-item.jsx)

**Comment by paulathevalley** [comment]
@coopy Are these being replaced by `radium-grid`? (And thus, this issue is dead?)

**Comment by coopy** [comment]
If @paulathevalley, @alexlande, @tptee and @mdaxtman agree that `radium-grid` can cover every use case for us, then let's kill this story and remove the Flex components as we replace them.

If there's still room for the Flex components as a less-complex layout tool, then we should consider making them part of the `radium-*` suite.

**Comment by tptee** [comment]
I think radium-grid is great for things that scream "grid" (content layout, rectangular sections, actual grids). It's the wrong fit for navigation bars and anything where intrinsic content size matters, and this is where Flexbox shines. I think there's room for a `radium-flex` in the future.

Personally, I don't know what <Flex> buys us over Radium and vanilla Flexbox, but I haven't used it enough to see the benefits.

**Comment by paulathevalley** [comment]
Since the builder docs is using `radium-grid` and formidable.com is going to be redesigned & relaunched, these components are super dead as is this ticket!
