### ISSUE TITLE
Create static site archetype

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/formidable-landers#57]
We've got a cool static site build pipeline for the Victory & Builder landers, and formidable.com. Let's make it repeatable by creating an archetype with `builder-init` boilerplate and everything. Call it `builder-static-react-site`

**Comment by david-davidson** [comment]
@coopy Great idea!

**Comment by paulathevalley** [comment]
Done! https://github.com/FormidableLabs/builder-docs-archetype
