### ISSUE TITLE
formidable-landers should depend on builder-react-component archetype

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/formidable-landers#65]
Even though f-l has multiple components, i think this makes sense. We should demo the components on the demo page.

**Comment by paulathevalley** [comment]
There is a task to demo the components on a demo page: `npm run demo`

I'm not sure this makes sense anymore. I have been thinking it would make more sense to move as many similar components as possible to `builder-docs-archetype` and delete `formidable-landers` altogether.
