### ISSUE TITLE
Add Radium screencast to lander page

### ISSUE THREAD

**Issue by elizagrace** [FormidableLabs/formidable-landers#69]
Would you like the raw file or the youtube link?

**Comment by paulathevalley** [comment]
We’ll embed the youtube video!

**Comment by elizagrace** [comment]
yay!

On Tue, Mar 1, 2016 at 2:22 PM, Paula Lavalle <notifications@github.com>
wrote:

> We’ll embed the youtube video!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FormidableLabs/formidable-landers/issues/69#issuecomment-190933361>
> .
>



-- 
*Eliza Grace*

*Formidable*
*eliza.grace@formidable.com <eliza.grace@formidable.com>*
