### ISSUE TITLE
Redirect stack.formidable.com to formidable.com/open-source

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#71]
For better SEO! 
- [ ] Redirect stack.formidable to formidable.com/open-source
- [ ] Support stack.formidable.com/foo redirect to formidable.com/open-source/foo

**Comment by elizagrace** [comment]
wonderful!

**Comment by paulathevalley** [comment]
@elizagrace :+1: If there are any inbound links going to stack.formidable.com that we need to redirect, would you add them here please so we can keep track of them?

**Comment by paulathevalley** [comment]
[stack.formidable.com](http://stack.formidable.com/) is our custom domain name for [formidablelabs.github.io](http://formidablelabs.github.io), in other words, it’s the same as: https://github.com/FormidableLabs/formidablelabs.github.io  

All the specific repos are "project" pages, which are normally served from {username}.github.io/{project-name}, but with our changes, that’s stack.formidable.com/{project-name}.

:question: Is it even possible to redirect [formidablelabs.github.io](http://formidablelabs.github.io) --> [formidable.com/open-source/](http://formidable.com/open-source)?  :question:

**Comment by ryan-roemer** [comment]
We don't control `formidablelabs.github.io`, so I'm guessing we can't redirect it in that way at the DNS protocol level.

**Comment by paulathevalley** [comment]
Ok! We will not be redirecting the subdomain. We will keep using github pages and the `stack.formidable.com` URL as a result.
