### ISSUE TITLE
Make victory docs responsive

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#79]
The component `svg`s have a fixed width of `450px` and height of `300px`. 

Maybe something with `standalone={false}` and `viewBox`? https://jsfiddle.net/scxm342c/2/ 

![screen shot 2016-03-10 at 9 31 13 pm](https://cloud.githubusercontent.com/assets/768965/13694174/726971be-e707-11e5-9538-ed7e26a09a7e.png)

**Comment by paulathevalley** [comment]
Ok, we can get the chart to take the full width of the preview box:
![screen shot 2016-03-25 at 5 47 20 pm](https://cloud.githubusercontent.com/assets/768965/14057022/a7d41d62-f2b1-11e5-894c-b397aaba8d40.png)

However, as you can compare, scales up the width of everything. Ideally, the grid will stay fixed. There is support for retaining the stroke width using `vector-effect="non-scaling-stroke"`, see:  https://www.w3.org/TR/SVGTiny12/painting.html#NonScalingStroke

I manually added them in devtools for the x-axis here:
![screen shot 2016-03-25 at 5 51 13 pm](https://cloud.githubusercontent.com/assets/768965/14057048/3280393c-f2b2-11e5-84ad-b5f3ff781a82.png)

**Comment by boygirl** [comment]
Do you think it would be reasonable to set the viewbox on the svg that victory components spit out by default. Does that seem like an overreach? Can you imagine a scenario where you _wouldn't_ want that? I guess we could just let people use `standalone={false}` and use their own container svg if they really dont want that.

**Comment by paulathevalley** [comment]
Yes. Since there are width and height props defined by default, I see no problem with setting `viewBox` to match it. The `viewBox` determines the aspect ratio, which everyone loves preserving. The only times I’ve run into the `viewBox` cutting off the artwork is when width and height were incorrectly or not defined.

On further research, it appears some browsers will [automatically scale inline SVGs](http://codepen.io/AmeliaBR/pen/ZYBmOG/?editors=1000 ) rendering the additional `width="100%"` useless. However, [some browsers released prior to the summer of 2014 do not](https://css-tricks.com/scale-svg/#article-header-id-9). So, we may want to add `width="100%"` or `height="100%"` by default. 

Also, the `vector-effect` SVG attribute is not supported until React v15. whomp whomp. Here’s what it will look like (text scaling looks ok!): http://codepen.io/paulathevalley/pen/Ragobo?editors=1100

**Comment by paulathevalley** [comment]
Closing via https://github.com/FormidableLabs/victory/issues/235
