### ISSUE TITLE
Add logos of companies using our OSS to their landing pages

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#82]
Add the logos of companies using our OSS to the appropriate landing pages. 

This is what I have: 

Victory: 
- [x] Viacom
- [x] Ookla
- [ ] NRC (maybe?)
- Spotify (https://github.com/spotify/reactochart) (not yet)

Radium: 
- [ ] NFL
- [ ] Twitter Ads
- [ ] Facebook
- [ ] Porch

Builder: 
- [ ] Walmart

@coopy Have you also been collecting this data? Is anything missing? 

Would it be worth creating an equivalent of [Sites Using React](https://github.com/facebook/react/wiki/Sites-Using-React) so that anyone can edit the page and add their name? 

/cc @boygirl @eastridge

**Comment by boygirl** [comment]
I think ookla is about to use Victory. I don't think Spotify is actually using it yet.

**Comment by alexlande** [comment]
> Would it be worth creating an equivalent of Sites Using React so that anyone can edit the page and add their name?

I think that would be cool :+1:

**Comment by eastridge** [comment]
We should curate, I dont think we should list everybody

On Thu, Apr 7, 2016 at 9:50 AM Alex Lande <notifications@github.com> wrote:

> Would it be worth creating an equivalent of Sites Using React so that
> anyone can edit the page and add their name?
>
> I think that would be cool [image: :+1:]
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/FormidableLabs/formidable-landers/issues/82#issuecomment-206989382>
>
--

**Comment by alexlande** [comment]
Agreed. I would think that "Sites Using [Radium/Victory/Builder]" would just be pages on the wikis of each of those projects, not logos we use promotionally.

**Comment by paulathevalley** [comment]
Added wiki pages: 
- [Sites Using Builder](https://github.com/FormidableLabs/builder/wiki/Sites-Using-Builder)
- [Sites Using Radium](https://github.com/FormidableLabs/radium/wiki/Sites-Using-Radium)
- [Sites Using Victory](https://github.com/FormidableLabs/victory/wiki/Sites-Using-Victory)

If you find any more uses, please add them there!

**Comment by paulathevalley** [comment]
Closing in favor of separate issues.
