### ISSUE TITLE
Create an archetype for all the -docs repos

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#85]
- [x] `builder-docs`: https://github.com/FormidableLabs/builder-docs/pull/20
- [x] `radium-docs`
- [x] `spectacle-docs`: https://github.com/FormidableLabs/spectacle-docs/pull/9
- [x] `victory-docs`

**Comment by paulathevalley** [comment]
Slam dunk! https://github.com/FormidableLabs/builder-docs-archetype

**Comment by kylecesmat** [comment]
radium-docs taken care of here - https://github.com/FormidableLabs/radium-docs/pull/4
