### ISSUE TITLE
Redirect adds extra slash

### ISSUE THREAD

**Issue by eastridge** [FormidableLabs/formidable-landers#92]
stack.formidable.com/victory

redirects to

http://formidable.com/open-source/victory//

**Comment by kylecesmat** [comment]
So this is somehow related to the SSR/React-Router configuration using `baseName`. When `href="/"` links are clicked after `builder run server-static`, they break with the error:
```
no-conflict.js:13 Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://localhost:8080' and URL 'http://localhost:8080/docs/guide'.
```
If that same link is clicked in production (/open-source/*) it simply appends an extra slash.

There is also a general error on the page for:
```
no-conflict.js:13 Warning: Automatically setting basename using <base href> is deprecated and will be removed in the next major release. The semantics of <base href> are subtly different from basename. Please pass the basename explicitly in the options to createHistory
```

This issue exists on victory-docs as well as radium-docs. It seems to do with the baseName being set, and react-router not knowing how to handle links to the index.
