### ISSUE TITLE
Make victory code examples look more editable

### ISSUE THREAD

**Issue by eastridge** [FormidableLabs/formidable-landers#93]
It's not immediately apparent that one can edit the code samples in the victory docs. Would recommend we change the style to make them look more editable. One option that would not require a change would be to auto focus each text area as you scroll past. In the case of the home page we could focus on the "1.5" and have the cursor be blinking there. I think this would encourage experimentation.

![screen shot 2016-05-08 at 12 37 30 pm](https://cloud.githubusercontent.com/assets/30921/15099955/d6623b52-1519-11e6-85ee-d4cb5f41a7ea.png)

**Comment by eastridge** [comment]
If it's too much of a PITA to generalize this we could do that as a one off on the home page.

**Comment by paulathevalley** [comment]
Change design: 
- Be able to add fixed height with scrolling 
- Full-width horizontal stripe 
- Remove borders on code blocks

**Comment by paulathevalley** [comment]
Design updated (homepage example will have a fixed height with scrolling): 

![screen shot 2016-06-08 at 10 33 56 am](https://cloud.githubusercontent.com/assets/768965/15904102/88a48880-2d64-11e6-948f-93d948fc5fa7.png)
