### ISSUE TITLE
Create a docs site for formidable-playbook

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#98]
- Use [formidable-playbook](https://github.com/FormidableLabs/formidable-playbook/)’s `README.md`

**Comment by coopy** [comment]
On the subject of URLs
`www.formidablelabs.com/playbook` would be cool
`www.formidablelabs.com/open-source/playbook` would be acceptable if it's much easier to solve technically.

**Comment by paulathevalley** [comment]
We only have server access to the `/open-source/` folder, so it would be much easier. Also, since the playbook is technically an open-source project, I would argue it belongs there despite its differences. 

As for requirements, here are my thoughts: 
- Create a route for each `.md` file that mimics the directory structure:
  - README.md -> `playbook/`
  - docs/frontend/webpack-code-splitting.md -> `playbook/docs/frontend/webpack-code-splitting`
  - docs/frontend/webpack-plugins.md -> `playbook/docs/frontend/webpack-plugins`
  - docs/infrastructure/single.md -> `playbook/docs/infrastructure/single`
  - and so on
- Follow the "space" style branding from [formidable.com](http://formidable.com/open-source/)
  - See unsplash for [spacey](https://unsplash.com/search?utf8=%E2%9C%93&keyword=space&button=)-[landscape]((https://unsplash.com/search?keyword=landscape)) inspiration, use Sharp Sans Bold No. 2, Akkurat Mono, and Tiempos Text, heavily rely on blacks/whites with minimal color
- Create an easily navigable layout (throwing out ideas: always visible sidebar, breadcrumbs showing current location, some kind of outline, or whatever!)
